name: github-workflow-1
on: workflow_dispatch
jobs:
  job-1:
    runs-on: ubuntu-latest
    steps:
      - name: print set-1
        run: echo "print set-1!"
      - name: print set-1
        run: |
          echo "Done.. set-1"
  job-2:
    runs-on: ubuntu-latest
    steps:
      - name: print set-2
        run: echo "print set-2!"
      - name: print set-2
        run: |
          echo "Done.. set-2"
  job-3:
    runs-on: ubuntu-latest
    steps:
      - name: print set-3
        run: echo "print set-3!"
      - name: print set-3
        run: |
          echo "Done.. set-3"
        
