name: github-workflow-1
on: push
jobs:
  job-1:
    needs: [job-4,job-5]
    runs-on: ubuntu-latest
    steps:
      - name: print set-1
        run: echo "print set-1!"
      - name: print set-1
        run: |
          echo "Done.. set-1"
  job-2:
    needs: [job-3]
    runs-on: ubuntu-latest
    steps:
      - name: print set-2
        run: echo "print set-2!"
      - name: print set-2
        run: |
          echo "Done.. set-2"
  job-3:
    needs: [job-4]
    runs-on: ubuntu-latest
    steps:
      - name: print set-3
        run: echo "print set-3!"
      - name: print set-3
        run: |
          echo "Done.. set-3"
  job-4:
    runs-on: ubuntu-latest
    steps:
      - name: print set-4
        run: echo "print set-4!"
      - name: print set-4
        run: |
          echo "Done.. set-4"
  job-5:
    runs-on: ubuntu-latest
    steps:
      - name: print set-5
        run: echo "print set-5!"
      - name: print set-5
        run: |
          echo "Done.. set-5"
        
